### ISSUE TITLE
Would it be possible to have the dependency upgrades under a major version change?

### ISSUE THREAD

**Issue by ghost** [jrit/web-resource-inliner#48]
Hey,

This library is a dependency on the library, [Juice](https://github.com/Automattic/juice) and it's on the package.json as:

`"web-resource-inliner": "^4.3.1"`

Due to that, the dependency upgrade of this library with the patch release 4.3.2 effectively made Juice incompatible with node v4.3 even though Juice still lists support on its package.json.

Since the project I'm working on is one of those dinosaurs that's still stuck on node v4.3, would it be possible to increment this library to v5 instead of 4.3.2 to denote breaking changes? Otherwise, the newest version of Juice that truly supports node v4.3 would be version 3.0.1, which was released 3 years ago.

Please let me know if I can provide a PR or if it would be more appropriate to bring this up as an issue on Juice's repository -- the change to `"web-resource-inliner": "~4.3.1"` would resolve my issue as well.

**Comment by jrit** [comment]
I think what I'll do, since I maintain Juice too, is make a patch on juice as 5.2.1 that uses web-resource-inliner at 4.3.2 specifically. That will be the last release of juice that supports node 4. Then I'll release juice 6.0.0 that will drop support for node 4 and uses the latest web-resource-inliner. I may not get to this today, but that's my plan. I think that is the proper way to semver this, but I'm open to suggestions.

**Comment by ghost** [comment]
That sounds perfect; thanks for looking into this!

**Comment by jrit** [comment]
There is a juice 5.1.9 on npm that uses wri 4.3.2 now. sorry, this is months overdue and I'm sure it was an inconvenience
