### ISSUE TITLE
Remove deprecated punycode throwing deprecation warning to stderr

### ISSUE THREAD

**Issue by alfonsrv** [jrit/web-resource-inliner#84]
I am using `mjml` which depends on `juice`, which in turn depends on `web-resource-inliner`,  throwing the following warning to `stderr`: `(node:60710) [DEP0040] DeprecationWarning: The "punycode" module is deprecated. Please use a userland alternative instead.`

`punycode` → `node-fetch` → `web-resource-inliner` → `juice`

Any alternative to work around this or way to fix this?

**Comment by iRyusa** [comment]
Sorry to ping you directly @jrit 

Seems like `node-fetch` could be easily replaced by native nodejs fetch ? I don't know if you could confirm this so I can try to make a PR for this

**Comment by jrit** [comment]
seems totally reasonable to me

**Comment by iRyusa** [comment]
Ok so I tried, it need a few changes to make it work. I'm down to a single test that doesn't work anymore.
`faux-jax` library doesn't work with `fetch` so I've replaced to `fetch-mock` that does almost the same thing. I'm still having 1 test that doesn't work fine with `fetch-mock` and i'm unsure if it's because of the mock or the code yet. 
I'll open the PR in WIP

**Comment by iRyusa** [comment]
All tests should pass now on that PR if you have time to test & release it as a major version that would be awesome 🙌
